name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          TF_VAR_k8s_host: ${{ secrets.K8S_HOST }}
          TF_VAR_k8s_token: ${{ secrets.K8S_TOKEN }}
          TF_VAR_k8s_ca_certificate: ${{ secrets.K8S_CA_CERTIFICATE }}

  deploy:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        run: |
          echo "${{ secrets.K8S_CA_CERTIFICATE }}" | base64 --decode > ca.crt
          echo "${{ secrets.K8S_TOKEN }}" > token
          kubectl config set-cluster my-cluster --server=${{ secrets.K8S_HOST }} --certificate-authority=ca.crt
          kubectl config set-credentials my-user --token=$(cat token)
          kubectl config set-context my-context --cluster=my-cluster --user=my-user
          kubectl config use-context my-context

      - name: Deploy Nginx
        run: |
          kubectl apply -f kubernetes/nginx-deployment.yaml
          kubectl apply -f kubernetes/nginx-service.yaml
